# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - function_parameter_count
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - anyobject_protocol # https://realm.github.io/SwiftLint/anyobject_protocol.html
  - closure_body_length # https://realm.github.io/SwiftLint/closure_body_length.html
  - closure_end_indentation # https://realm.github.io/SwiftLint/closure_end_indentation.html
  - closure_spacing # https://realm.github.io/SwiftLint/closure_spacing.html
  - collection_alignment # https://realm.github.io/SwiftLint/collection_alignment.html
  - contains_over_filter_count # https://realm.github.io/SwiftLint/contains_over_filter_count.html
  - contains_over_first_not_nil # https://realm.github.io/SwiftLint/contains_over_first_not_nil.html
  - convenience_type # https://realm.github.io/SwiftLint/convenience_type.html
  - discarded_notification_center_observer # https://realm.github.io/SwiftLint/discarded_notification_center_observer.html
  - discouraged_assert # https://realm.github.io/SwiftLint/discouraged_assert.html
  - discouraged_object_literal # https://realm.github.io/SwiftLint/discouraged_object_literal.html
  - duplicate_enum_cases # https://realm.github.io/SwiftLint/duplicate_enum_cases.html
  - empty_collection_literal # https://realm.github.io/SwiftLint/empty_collection_literal.html
  - empty_count # https://realm.github.io/SwiftLint/empty_count.html
  - empty_string # https://realm.github.io/SwiftLint/empty_string.html
  - empty_xctest_method # https://realm.github.io/SwiftLint/empty_xctest_method.html
  - enum_case_associated_values_count # https://realm.github.io/SwiftLint/enum_case_associated_values_count.html
  - expiring_todo # https://realm.github.io/SwiftLint/expiring_todo.html
  - explicit_init # https://realm.github.io/SwiftLint/explicit_init.html
  - fallthrough # https://realm.github.io/SwiftLint/fallthrough.html
  - fatal_error_message # https://realm.github.io/SwiftLint/fatal_error_message.html
  - file_name_no_space # https://realm.github.io/SwiftLint/file_name_no_space.html
  - file_types_order # https://realm.github.io/SwiftLint/file_types_order.html
  - first_where # https://realm.github.io/SwiftLint/first_where.html
  - flatmap_over_map_reduce # https://realm.github.io/SwiftLint/flatmap_over_map_reduce.html
  - force_unwrapping # https://realm.github.io/SwiftLint/force_unwrapping.html
  - identical_operands # https://realm.github.io/SwiftLint/identical_operands.html
  - implicit_return # https://realm.github.io/SwiftLint/implicit_return.html
  - joined_default_parameter # https://realm.github.io/SwiftLint/joined_default_parameter.html
  - last_where # https://realm.github.io/SwiftLint/last_where.html
  - legacy_objc_type # https://realm.github.io/SwiftLint/legacy_objc_type.html
  - legacy_random # https://realm.github.io/SwiftLint/legacy_random.html
  - literal_expression_end_indentation # https://realm.github.io/SwiftLint/literal_expression_end_indentation.html
  - lower_acl_than_parent # https://realm.github.io/SwiftLint/lower_acl_than_parent.html
  # - missing_docs # https://realm.github.io/SwiftLint/missing_docs.html
  - modifier_order # https://realm.github.io/SwiftLint/modifier_order.html
  - multiline_arguments # https://realm.github.io/SwiftLint/multiline_arguments.html
  - multiline_function_chains # https://realm.github.io/SwiftLint/multiline_function_chains.html
  - multiline_literal_brackets # https://realm.github.io/SwiftLint/multiline_literal_brackets.html
  - multiline_parameters # https://realm.github.io/SwiftLint/multiline_parameters.html
  - no_extension_access_modifier # https://realm.github.io/SwiftLint/no_extension_access_modifier.html
  - number_separator # https://realm.github.io/SwiftLint/number_separator.html
  - object_literal # https://realm.github.io/SwiftLint/object_literal.html
  - operator_usage_whitespace # https://realm.github.io/SwiftLint/operator_usage_whitespace.html
  - prefer_self_type_over_type_of_self # https://realm.github.io/SwiftLint/prefer_self_type_over_type_of_self.html
  - prefer_zero_over_explicit_init # https://realm.github.io/SwiftLint/prefer_zero_over_explicit_init.html
  - private_action # https://realm.github.io/SwiftLint/private_action.html
  - private_outlet # https://realm.github.io/SwiftLint/private_outlet.html
  - reduce_into # https://realm.github.io/SwiftLint/reduce_into.html
  - redundant_nil_coalescing # https://realm.github.io/SwiftLint/redundant_nil_coalescing.html
  - redundant_type_annotation # https://realm.github.io/SwiftLint/redundant_type_annotation.html
  - single_test_class # https://realm.github.io/SwiftLint/single_test_class.html
  - sorted_first_last # https://realm.github.io/SwiftLint/sorted_first_last.html
  - toggle_bool # https://realm.github.io/SwiftLint/toggle_bool.html
  - trailing_closure # https://realm.github.io/SwiftLint/trailing_closure.html
  - type_contents_order # https://realm.github.io/SwiftLint/type_contents_order.html
  - unavailable_function # https://realm.github.io/SwiftLint/unavailable_function.html
  - unneeded_parentheses_in_closure_argument # https://realm.github.io/SwiftLint/unneeded_parentheses_in_closure_argument.html
  - unowned_variable_capture # https://realm.github.io/SwiftLint/unowned_variable_capture.html
  - unused_import # https://realm.github.io/SwiftLint/unused_import.html
  - vertical_parameter_alignment_on_call # https://realm.github.io/SwiftLint/vertical_parameter_alignment_on_call.html
  - vertical_whitespace_closing_braces # https://realm.github.io/SwiftLint/vertical_whitespace_closing_braces.html
  - vertical_whitespace_opening_braces # https://realm.github.io/SwiftLint/vertical_whitespace_opening_braces.html
  - yoda_condition # https://realm.github.io/SwiftLint/yoda_condition.html

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build/
  - .swiftpm/
  - Package.swift
  - .swiftlint.yml
  - Sources/CucumberSwiftExpressions/CucumberSwiftExpressions.docc

line_length:
  warning: 191
  error: 220
  ignores_comments: true

nesting:
  type_level: 2

switch_case_alignment:
  indented_cases: true

cyclomatic_complexity:
  ignores_case_statements: true

type_contents_order:
  order: [
      [SwiftLintFramework.TypeContent.case],
      [
        SwiftLintFramework.TypeContent.typeAlias,
        SwiftLintFramework.TypeContent.associatedType,
      ],
      [SwiftLintFramework.TypeContent.subtype],
      [SwiftLintFramework.TypeContent.typeProperty],
      [SwiftLintFramework.TypeContent.instanceProperty],
      [SwiftLintFramework.TypeContent.typeMethod],
      # [SwiftLintFramework.TypeContent.ibInspectable],
      # [SwiftLintFramework.TypeContent.ibOutlet],
      [SwiftLintFramework.TypeContent.initializer],
      [SwiftLintFramework.TypeContent.deinitializer],
      [SwiftLintFramework.TypeContent.viewLifeCycleMethod],
      [
        SwiftLintFramework.TypeContent.ibAction,
        SwiftLintFramework.TypeContent.otherMethod,
        SwiftLintFramework.TypeContent.subscript,
      ],
    ]

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
