name: CI

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: swift test -v --enable-code-coverage
      - name: Convert code coverage
        run: xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name CucumberSwiftExpressionsPackageTests) > info.lcov
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: info.lcov
          fail_ci_if_error: true

  build_for_package_managers:
    needs: test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Validate SwiftPM BUILDs
        run: fastlane build_swiftpm
      - name: Bundle install
        run: bundle install
      - name: Validate Cocoapods Can Deploy (lib lint)
        run: fastlane cocoapods_liblint